# deploy/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helios-v3-core-api
  namespace: helios-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helios-v3-core-api
  template:
    metadata:
      labels:
        app: helios-v3-core-api
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: tls-cloudflare-2024
      containers:
      - name: helios-v3-core-api
        image:  medcase.azurecr.io/helios/helios-core:v310
        volumeMounts:
            - name: secret-volume
              mountPath: "/etc/ssl/certs"
              readOnly: true
        ports:
          - containerPort: 8080
          - containerPort: 8001
        env:
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/etc/ssl/certs/tls.crt" # Path to the mounted certificate
        - name: ASPNETCORE_Kestrel__Certificates__Default__KeyPath
          value: "/etc/ssl/certs/tls.key" # Path to the mounted key
        - name: ASPNETCORE_HTTPS_PORTS
          value: "8081" # Path to the mounted certificate
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080" # Path to the mounted key
        - name: ASPNETCORE_URLS
          value: "http://+:8080;https://+:8081"
          # value: "http://+:8080;https://+:8081"
        - name: Services__Auth
          value: "http://10.7.0.5:80"
        - name: Services__Shared
          value: "http://10.7.0.6:80"
---
apiVersion: v1
kind: Service
metadata:
  name: helios-v3-core-api
  namespace: helios-testing
  # annotations:
    # appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    # appgw.ingress.kubernetes.io/override-frontend-port: "true"
spec:
  selector:
    app: helios-v3-core-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8081
  type: ClusterIP
