version: '3.4'

services:
  helios.ecrf:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3300:3300"
      - "3301:3301"

  helios.authentication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
        - "8080:8080"
        - "8081:8081"

  helios.core:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3500:3500"
      - "3501:3501"
