version: '3.4'

services:
  helios.ecrf:
    image: ${DOCKER_REGISTRY-}heliosecrf
    build:
      context: .
      dockerfile: Helios.EDC/Helios.eCRF/Dockerfile
    ports:
     - 2000:80
     - 2001:443
    networks:
        vpcbr:
            ipv4_address: 10.5.0.2

  helios.authentication:
    image: ${DOCKER_REGISTRY-}heliosauthentication
    build:
      context: .
      dockerfile: Helios.Authentication/Dockerfile
    ports:
     - 3000:80
     - 3001:443
    networks:
        vpcbr:
            ipv4_address: 10.5.0.3


  helios.core:
    image: ${DOCKER_REGISTRY-}helioscore
    build:
      context: .
      dockerfile: Helios.EDC/Helios.Core/Dockerfile
    ports:
     - 4000:80
     - 4001:443
    networks:
        vpcbr:
            ipv4_address: 10.5.0.4

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1