version: '3.4'

services:
  helios.ecrf:
    image: ${DOCKER_REGISTRY-}heliosecrf
    build:
      context: .
      dockerfile: Helios.EDC/Helios.eCRF/Dockerfile
    ports:
     - 3200:80
     - 3201:443
    networks:
        vpcbr:
            ipv4_address: 10.7.0.3

  helios.authentication:
    image: ${DOCKER_REGISTRY-}heliosauthentication
    build:
      context: .
      dockerfile: Helios.Authentication/Dockerfile
    ports:
     - 5200:80
     - 5201:443
    networks:
        vpcbr:
            ipv4_address: 10.7.0.5


  helios.core:
    image: ${DOCKER_REGISTRY-}helioscore
    build:
      context: .
      dockerfile: Helios.EDC/Helios.Core/Dockerfile
    ports:
     - 4200:80
     - 4201:443
    networks:
        vpcbr:
            ipv4_address: 10.7.0.4

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.7.0.0/16
         gateway: 10.7.0.1