version: '3.4'

services:

  helios.authentication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
        - "8080:8080"
        - "8081:8081"

  helios.core:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3500:8080"
      - "3501:8081"

networks:
  v3network:
     name: v3network