trigger:
  branches:
    include:
      - main

pool:
  name: 'vmssagents-pool'



variables:
 
  # Azure Container Registry details
  acrName: 'medcase'
  registry: 'medcase.azurecr.io'
  tag: '$(Build.BuildId)'

  # Kubernetes details
  aksClusterName: 'medcase-cluster-dev'
  kubernetesNamespace: 'helios-testing'  # e.g., production
  azureServiceConnection: 'Medcase-Azure-Cli' 
  dockerRegistryServiceConnection: 'medcase'
steps:
- checkout: self  # This is the correct way to reference the checkout step

- script: |
    echo "Current user: $(whoami)"
    id
  displayName: 'Check user details'

# - script: |
#     sudo usermod -a -G docker $(whoami)

#     whoami
#     groups
#     sudo chown root:docker /var/run/docker.sock
#     sudo chmod 660 /var/run/docker.sock
#     ls -R .
    
#   env:
#     cid: $(CLIENTID) 
#     cs: $(CLIENTSECRET)
#     tt: $(TENANTID)
#   displayName: 'Verify Docker Installation'

- script: |
    echo "Installing Azure CLI..."
    apt-get install -y azure-cli
    az --version
  displayName: 'Install Azure CLI'
  
- script: |
    az --version
  displayName: 'Verify Azure CLI Installation'

- script: |
    az login --service-principal -u $(CLIENTID) -p $(CLIENTSECRET) --tenant $(TENANTID)
  displayName: 'Login Azure CLI'

- script: |
    ls -R /var/lib/docker
    echo "Listing files..."
    ls -R .
    if [ ! -f "./Helios.sln" ]; then
      echo "Project file not found!"
      exit 1
    fi
     if [ ! -f "./pipeline/build-docker.sh" ]; then
      echo "build-docker.sh file not found!"
      exit 1
    fi
  displayName: 'Verify project file exists'

- script: |
    sudo usermod -aG docker $(whoami)

    newgrp docker << EOF

    echo 'Running acr login ....'
    az acr login --name $(acrName)
    
    # Your Docker commands here
    docker build -t helios-core:$(tag) -f './Helios.EDC/Helios.Core/Dockerfile' .
    # Tag the image with the registry
    docker tag helios-core:$(tag) medcase.azurecr.io/helios/helios-core:$(tag)

    # Push the image to the Azure Container Registry
    docker push medcase.azurecr.io/helios/helios-core:$(tag)

    EOF
  displayName: '[Core Api] Build and Push Docker Image'

- task: Kubernetes@1
  displayName: 'Deploy to AKS'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Medcase-Azure-Cli'
    azureResourceGroup: 'medcase-cluster'
    kubernetesCluster: '$(aksClusterName)'
    namespace: '$(kubernetesNamespace)'
    command: 'apply'
    useConfigurationFile: false
    arguments: |
      -f deploy/deployment-core.yaml
    secretType: 'None'