trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Docker image details
  imageName: 'helios-core'

  # Azure Container Registry details
  acrName: 'medcase'
  acrLoginServer: 'medcase.azurecr.io'
  tag: '$(Build.BuildId)'

  # Kubernetes details
  aksClusterName: 'medcase-cluster-dev'
  kubernetesNamespace: 'helios-testing'  # e.g., production

steps:
- checkout: self  # This is the correct way to reference the checkout step

- script: |
    echo "Running the build process..."
  displayName: 'Build the application'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Medcase-Azure-Cli'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Listing images in ACR..."
      az acr repository list --name $(acrName) --output table

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    containerRegistry: '$(acrName)'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '.'
    tags: |
      $(tag)
      latest



- task: Kubernetes@1
  displayName: 'Deploy to AKS'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'AKSConnection'
    azureResourceGroup: 'your-resource-group'
    kubernetesCluster: '$(aksClusterName)'
    namespace: '$(kubernetesNamespace)'
    command: 'apply'
    useConfigurationFile: false
    arguments: |
      -f deploy/deployment-core.yaml
    secretType: 'None'