namespace Helios.Common.Enums
{
    public enum VisitPermission
    {
        Freeze = 3,
        Lock = 4,
        Signature = 5,
        SDV = 6,
        Query = 7,
        Verification = 8,
        SAELock = 9,
    }

    public enum StudyRolePermission
    {
        Add = 100,
        View = 101,
        Edit = 102,
        ArchivePatient = 103,
        PatientStateChange = 104,
        Randomize = 105,
        ViewRandomization = 106,
        Sdv = 107,
        Sign = 108,
        Lock = 109,
        MarkAsNull = 110,
        QueryView = 111,
        AutoQueryClosed = 112,
        CanFileView = 113,
        CanFileUpload = 114,
        CanFileDeleted = 115,
        CanFileDownload = 116,
        StudyFoldersView = 117,
        ExportData = 118,
        DashboardView = 119,
        InputAuditTrail = 120,
        AERemove = 121,
        IwrsMarkAsRecieved = 122,
        IwrsTransfer = 123,
        ApproveSourceDocuments = 124,
        Monitoring = 125,
        ApproveAudit = 126,
        Audit = 127,
        CanSeeCycleAuditing = 128,
        CanSeeCycleMonitoring = 129,
        CanSeePatientAuditing = 130,
        CanSeePatientMonitoring = 131,
        CanSeeSiteAuditing = 132,
        CanSeeSiteMonitoring = 133,
        UploadAuditing = 134,
        UploadMonitoring = 135,
        RemoteSdv = 136,
        HasPageFreeze = 137,
        HasPageUnFreeze = 138,
        HasPageUnLock = 139,
        SeePageActionAudit = 140,
        CanCode = 141,
        RemovePatient = 142,
        AEArchive = 143,
        ArchiveMultiVisit = 144,
        RemoveMultiVisit = 145,
        DoubleDataCompare = 146,
        DoubleDataEntry = 147,
        DoubleDataReport = 148,
        DoubleDataViewAll = 149,
        DoubleDataDelete = 150,
        DoubleDataQuery = 151,
        DoubleDataAnswerQuery = 152,
        DashboardBuilderAdmin = 153,
        DashboardBuilderPivotExport = 154,
        DashboardBuilderSourceExport = 155,
        TmfAdmin = 156,
        TmfSiteUser = 157,
        TmfUser = 158,
        MriPage = 159,
        EConsentView = 160,
        ExportPatientForm = 161,
        AddAdverseEvent = 162,
        AddMultiVisit = 163
    }
}
